services:
    web:
        build:
            dockerfile: nginx/Dockerfile
        ports: 
          - "80:80"
          - "443:443"
        restart: unless-stopped
        tty: true
        volumes: 
          - ./public:/var/www/html/public
          - letsencrypt_gss:/etc/letsencrypt
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/certs:/etc/nginx/certs
        networks:
          - example-net
        depends_on:
          - app  
          - redis      
    
    app:
        build:
            dockerfile: Dockerfile
        volumes:
          - ./public:/var/www/html/public
          - ./php/php.ini:/usr/local/etc/php/php.ini
        networks:
          - example-net
        restart: unless-stopped
        tty: true
        depends_on:
          - db
          - redis
    
    sse:
        build:
            dockerfile: sse/Dockerfile
        volumes:
          - ./sse:/home/node/app
        networks:
          - example-net
        restart: unless-stopped
        tty: true
        depends_on:
          - db
          - redis
        ports:
          - 8080:8080

    redis:
        image: redis:latest
        restart: always
        volumes:
          - redis_volume_gss:/data
        ports:
          - 6379:6379
        networks:
          - example-net

    redis_insight: 
        image: redislabs/redisinsight:latest
        restart: always
        volumes:
          - redis_insight_volume_gss:/db
        ports:
          - 8001:5540
        depends_on:
          - redis
        networks:
          - example-net
       
    db:
        image: mysql:8.0
        volumes: 
          - mysqldata_gss:/var/lib/mysql
        ports:
          - "3308:3306"
        networks:
          - example-net
        restart: unless-stopped
        command: --max_allowed_packet=325058560
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: cbt
    
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 5147:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 12345678
            UPLOAD_LIMIT: 1G
        depends_on:
          - db
        networks:
          - example-net

volumes:
    mysqldata_gss:
    letsencrypt_gss:
    redis_volume_gss:
    redis_insight_volume_gss:

networks:
  example-net:
    driver: bridge
    name: example-net
    external: true