services:
    web:
        build:
            dockerfile: nginx/Dockerfile
        ports: 
          - "80:80"
          - "443:443"
        restart: unless-stopped
        tty: true
        volumes: 
          - ./:/var/www/html
          - letsencrypt:/etc/letsencrypt
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
          vlan:
            ipv4_address: 192.168.0.105
        depends_on:
          - app        
    app:
        build:
            dockerfile: Dockerfile
        volumes:
          - ./php/php.ini:/usr/local/etc/php/php.ini
        networks:
          vlan:
            ipv4_address: 192.168.0.101
        restart: unless-stopped
        tty: true
        depends_on:
          - db
       
    db:
        image: mysql:8.0
        volumes: 
          - mysqldata:/var/lib/mysql
        ports:
          - "3308:3306"
        networks:
          vlan:
            ipv4_address: 192.168.0.102
        restart: unless-stopped
        command: --max_allowed_packet=325058560
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: cbt
    
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 5147:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 12345678
            UPLOAD_LIMIT: 100000000
        depends_on:
          - db
        networks:
          vlan:
            ipv4_address: 192.168.0.103

volumes:
    mysqldata:
    letsencrypt:

networks:
  vlan:
    external: true
    name: vlan


    