services:
    web:
        image: nginx:latest
        ports: 
          - "80:80"
        restart: unless-stopped
        tty: true
        volumes: 
          - ./:/var/www/html
          - ./nginx/sites-available/conscal.site.conf:/etc/nginx/sites-available/conscal.site.conf
          - ./nginx/sites-enabled/conscal.site.conf:/etc/nginx/sites-available/conscal.site.conf
        networks:
          - example-net
        depends_on:
          - app
        
    app:
        build:
            dockerfile: Dockerfile
        volumes:
          - ./:/var/www/html
        networks:
          - example-net
        restart: unless-stopped
        tty: true
        depends_on:
          - db
       
    db:
        image: mysql:8.0
        volumes: 
          - mysqldata:/var/lib/mysql
        ports:
          - "3308:3306"
        networks:
          - example-net
        restart: unless-stopped
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: cbt
volumes:
    mysqldata:

networks:
  example-net:
    driver: bridge