services:
    web:
        image: nginx:latest
        ports: 
          - "80:80"
        restart: unless-stopped
        tty: true
        volumes: 
          - ./:/var/www/html
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
          - example-net
        depends_on:
          - app
        
    app:
        build:
            dockerfile: Dockerfile
        volumes:
          - ./:/var/www/html
        networks:
          - example-net
        restart: unless-stopped
        tty: true
        depends_on:
          - db
       
    db:
        image: mysql:8.0
        volumes: 
          - mysqldata:/var/lib/mysql
        ports:
          - "3308:3306"
        networks:
          - example-net
        restart: unless-stopped
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: cbt
    
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 5147:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 12345678
        depends_on:
          - db
        networks:
          - example-net

volumes:
    mysqldata:

networks:
  example-net:
    driver: bridge