services:
    web:
        image: nginx:latest
        ports: 
          - "80:80"
          - "443:443"
        restart: unless-stopped
        tty: true
        volumes: 
          - ./:/var/www/html
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
          - example-net
        depends_on:
          - app
        
    app:
        build:
            dockerfile: Dockerfile
        # command: 'php artisan serve --host=0.0.0.0'
        volumes:
          - ./:/var/www/html
        networks:
          - example-net
        restart: unless-stopped
        tty: true
       
    db:
        image: mysql:8.0
        volumes: 
          - mysqldata:/var/lib/mysql
        ports:
          - "3308:3306"
        networks:
          - example-net
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: cbt
volumes:
    mysqldata:

networks:
  example-net:
    driver: bridge