version: '3.8'
services:
  nginx_proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    networks:
      - example-net
    volumes:
      - ./:/var/www/html
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt


networks:
  example-net:
    driver: bridge